### ISSUE TITLE
Hackage release for GHC 8

### ISSUE THREAD

**Issue by travitch** [mainland/ref-tf#1]
Would it be possible to get a release to hackage with the transformers version bump for ghc 8?

**Comment by nitrix** [comment]
To the risk of being annoying, I have the same request. It's blocking a long chain of packages :)

**Comment by mainland** [comment]
Sorry, I hadn't realized I had never actually uploaded the GHC 8-compatible release to hackage!

**Comment by travitch** [comment]
Thanks!
