### ISSUE TITLE
Add ref-tf to Stackage?

### ISSUE THREAD

**Issue by sjakobi** [mainland/ref-tf#3]
`hnix`, which I would like to put on Stackage (https://github.com/commercialhaskell/stackage/pull/5429) in order to make it easy to install for `stack` users, depends on `ref-tf`.

Would you consider adding `ref-tf` to Stackage? You can find instructions [here](https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md#adding-a-package).

**Comment by mainland** [comment]
Done! See commercialhaskell/stackage#5497.

I didn't know anyone was using this package...glad to see you've found it useful!

**Comment by mainland** [comment]
Ah, I see you have taken ownership of `ref-tf` instead. I will go ahead and close this issue.

**Comment by sjakobi** [comment]
Apologies for not updating you on this!

If `ref-tf` runs into any trouble on Stackage, I will notify you, and we can consider moving it to your "ownership" then.
